image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - aaron-bond.better-comments
    - bungcip.better-toml
    - GitHub.copilot
    - gitpod.gitpod-desktop
    - googlecloudtools.cloudcode
    - hbenl.vscode-test-explorer
    - k--kato.intellij-idea-keybindings
    - mechatroner.rainbow-csv
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode.test-adapter-converter
    - mushan.vscode-paste-image
    - Perkovec.emoji
    - RandomFractalsInc.vscode-data-preview
    - redhat.vscode-yaml
    - stylelint.vscode-stylelint
    - Tim-Koehler.helm-intellisense
    - toba.vsfire
    - wix.vscode-import-cost
    - zxh404.vscode-proto3
    - golang.go