name: Build Docker images, push to Docker Hub

on:
  push:
    tags:
      - "*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: langameai
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to OVHCloud Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.OVHCLOUD_REGISTRY }}
          username: ${{ secrets.OVHCLOUD_REGISTRY_USERNAME }}
          password: ${{ secrets.OVHCLOUD_REGISTRY_PASSWORD }}
      - 
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            langameai/search-engine:latest
            langameai/search-engine:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/search-engine:latest
            ghcr.io/${{ github.repository_owner }}/search-engine:${{ steps.get_version.outputs.VERSION }}
            ${{ secrets.OVHCLOUD_REGISTRY }}/prod/search-engine:latest
            ${{ secrets.OVHCLOUD_REGISTRY }}/prod/search-engine:${{ steps.get_version.outputs.VERSION }}
      - 
        name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_REPOSITORY: ${{ github.repository_owner }}/search-engine